feat(deployment/daemonset): Add option for resources
rancher/vsphere-charts pull request #71
Opened 2024-04-09 12:39 UTC by Mart-Kuc

#### Pull Request Checklist ####

- [ ] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [ ] Chart version has been incremented (if necessary)
- [x] That helm lint and pack run successfully on the chart.
- [x] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####
- Add support for settings resources for all pods in `deployment` and `daemonset`.
- Using resource limits/requests is best practices and is recommended.
- Default values in `values.yaml` is blank for all images, so no breaking change and full compatibility is maintained

#### Linked Issues ####
None
#### Additional Notes ####

- Tested on vSphere Client v. 8.0.2, K8S v1.27.12, provider RKE2.
- Helm lint
![Screenshot from 2024-04-09 14-28-56](https://github.com/rancher/vsphere-charts/assets/52672224/221c4885-b626-435e-a1cf-8b7777a06da1)

**Importance notes**
- Version of Char has not been changed due to more PR
- `Limits` and `Requests` in `resources` comments are only for example. I don't recommended to use these values in production.

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

2024-09-02 06:41 UTC, pvlkov commented
Is this happening any time soon? The PR has been sitting here for 5 months now...We would really appreciate the possibility to set resource requests on system critical daemonsets.

2024-09-04 19:26 UTC, jiaqiluo approved these changes
LGTM

2024-09-04 19:46 UTC, jiaqiluo requested changes
Could you rebase the PR and bump the `version` in the Chart.yaml ?

2024-09-05 08:51 UTC, brandond commented
You'll need to rebase again after that one is merged, at which point what version to use should be clear... just N+1 of whatever your change is based off of.

2024-09-06 09:57 UTC, Mart-Kuc commented
Rebased and bumped Chart version

2024-09-06 17:02 UTC, jiaqiluo submitted a review, later dismissed

2024-09-11 06:43 UTC, Mart-Kuc commented
Bumped version of `Chart` and  `App`. Resolved conflicts

2024-09-11 18:26 UTC, jiaqiluo approved these changes

2024-09-11 18:31 UTC, jiaqiluo commented
Hi @brandond, could you re-review this PR?

2024-09-11 18:53 UTC, merged