feat(deployment/daemonset): Remove imagePullPolicy from charts
rancher/vsphere-charts pull request #72
Opened 2024-04-09 13:07 UTC by Mart-Kuc

#### Pull Request Checklist ####

- [ ] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [ ] Chart version has been incremented (if necessary)
- [x] That helm lint and pack run successfully on the chart.
- [x] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####
- Remove `ImagePullPolicy: "Always"` from `daemonset` and `deployment`

According to [documentation](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) if you specify version of image tag, automatically ImagePullPolicy is set to `IfNotPressent`.
And vice versa if you not specify version of image tag (keep latest) ImagePullPolicy is set to `Always`.

So keep ImagePullPolicy hard coded to `Always` in charts does not make sense.
It overrides to `Always` even if image tag is defined.

#### Linked Issues ####

#### Additional Notes ####
- Helm lint

![Screenshot from 2024-04-09 15-07-19](https://github.com/rancher/vsphere-charts/assets/52672224/43285fc1-c5cc-4fbf-913a-e1cf569fcfc9)

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

2024-09-05 21:05 UTC, jiaqiluo commented
Hi @Mart-Kuc, according to [k8s documentation](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting), the overwriting happens only when the ImagePullPolicy is not specified. So setting `ImagePullPolicy: "Always"` actually takes effect and works as expected. 

Please correct me if I misunderstand anything.

2024-09-06 16:16 UTC, jiaqiluo commented
Hi @Mart-Kuc, yeah, it makes sense.  Just for clarification, the tag `latest` will never be used because the value will be overwritten by a specific tag from the  `versionOverrides` section.  

Instead of removing the `ImagePullPolicy` line from both files, could you convert it to a new option in the `value.yaml` and set the default value ("") , under `csiController` and `csiNode` sections? It will provide some flexibility for users who needs it.

2024-09-09 16:46 UTC, jiaqiluo requested changes
The changes look good to me! 
There is one last charge we need to add:  bumping the `appVersion` and `version` in the `Chart.yaml` file as we are making changes to the chart. Could you bump those two fields to `3.3.1-rancher3`?

2024-09-10 10:36 UTC, Mart-Kuc commented
Bumped

2024-09-10 15:57 UTC, jiaqiluo commented
Hi @brandond, could you review this PR? We need two approvals before merging it.

2024-09-10 22:38 UTC, brandond approved these changes

2024-09-10 22:40 UTC, merged