Update csi/cpi images for k8s 1.29 support
rancher/vsphere-charts pull request #81
Opened 2024-06-10 07:40 UTC by krunalhinguu

#### Pull Request Checklist ####

- [ ] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [ ] Chart version has been incremented (if necessary)
- [ ] That helm lint and pack run successfully on the chart.
- [ ] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

- Images has been bumped for vsphere-csi and vsphere-cpi to support k8s 1.29.

#### Linked Issues ####

- https://github.com/rancher/rancher/issues/45463
- https://github.com/rancher/rancher/issues/45464

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

2024-06-11 02:46 UTC, snasovich requested changes
One comment to address.
Also CI is failing - looks like one of the tests needs to be updated (or maybe it's catching actual issue? 🤷 )
https://github.com/rancher/vsphere-charts/actions/runs/9444377823/job/26054730155#step:5:1200

2024-06-11 03:04 UTC, krunalhinguu commented on charts/rancher-vsphere-csi/values.yaml
> +  - constraint: ">= 1.29 < 1.30"
Let me update it.

2024-06-11 03:06 UTC, krunalhinguu commented
Looks like there is some struct change with kubelet:1.29. I look into it today. @snasovich

2024-06-11 14:55 UTC, snasovich approved these changes
@krunalhinguu , LGTM now - thank you for updating the versions range and fixing YAML formatting to get CI to pass (tests are actually helpful!).

2024-06-11 17:28 UTC, brandond commented
Can we add CPI 1.30 support here as well? It has been available for ~3 weeks now.
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.30.1

2024-06-11 22:59 UTC, snasovich commented
> Can we add CPI 1.30 support here as well? It has been available for ~3 weeks now. [kubernetes/cloud-provider-vsphere@`v1.30.1` (release)](https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.30.1)

@brandond , this is planned to be done as part of https://github.com/rancher/rancher/issues/45746 but I wouldn't mind if it's rolled into this PR. @krunalhinguu , up to you if you want to tack it onto this PR or open a separate one.

2024-06-12 04:39 UTC, krunalhinguu commented
sure @snasovich . Adding 1.30 support for CPI as part of this PR as it wont make much difference raising in separate PR

2024-06-13 15:24 UTC, snasovich approved these changes
LGTM

2024-06-13 16:26 UTC, brandond approved these changes

2024-06-13 16:26 UTC, merged