Add K8s 1.31 support for CPI and CSI
rancher/vsphere-charts pull request #88
Opened 2024-08-26 15:24 UTC by dereknola

#### Pull Request Checklist ####

- [ ] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [ ] Chart version has been incremented (if necessary)
- [ ] That helm lint and pack run successfully on the chart.
- [ ] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

#### Linked Issues ####
https://github.com/rancherlabs/eio/issues/2559

#### Additional Notes ####

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

2024-08-26 18:05 UTC, brandond approved these changes

2024-08-27 01:47 UTC, jiaqiluo requested changes

2024-08-27 01:47 UTC, jiaqiluo commented on charts/rancher-vsphere-csi/Chart.yaml
let's bump the `appVersion` and `version` to  3.3.0-rancher**3**. 

It seems that the value `3.3.0` is from the upstream release tag [v3.3.0](https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.3.0) where is the source of the templates.

2024-08-28 20:59 UTC, jiaqiluo requested changes

2024-08-28 20:59 UTC, jiaqiluo commented on charts/rancher-vsphere-csi/Chart.yaml
> +version: 3.3.0-rancher3
I notice the image tag for `rancher/mirrored-cloud-provider-vsphere-csi-release-driver` and `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer` are bumped to  v3.3.1, 
Could you bump the version and appVersion to `3.3.1-rancher1`? 

Side note: there are no changes except image tags in the file `vsphere-csi-driver.yaml` between the upstream release 3.3.1 and 3.3.0 (l[ink](https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v3.3.0...v3.3.1)), which is good.

2024-08-28 21:05 UTC, jiaqiluo approved these changes
LGTM. 

There are no changes except image tags in the file `vsphere-csi-driver.yaml` between the upstream release 3.3.1 and 3.3.0 (l[ink](https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v3.3.0...v3.3.1)), so nothing except image tags to be updated in the charts.

2024-08-28 21:21 UTC, brandond approved these changes

2024-08-28 21:22 UTC, merged