feat(json): add support for json
rancher/vsphere-charts pull request #96
Opened 2024-10-22 11:14 UTC by dmpe

#### Pull Request Checklist ####

- [ ] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [ ] Chart version has been incremented (if necessary)
- [ ] That helm lint and pack run successfully on the chart.
- [ ] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

#### Linked Issues ####

#### Additional Notes ####

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

2024-10-23 15:23 UTC, snasovich commented
@dmpe , I see you opened this draft PR - thank you for working on this enhancement.

Before you go too far into implementing it, I'm wondering if it's a good idea to adopt a more generic approach where one can specify an array in something like `.Values.csiNode.image.nodeDriverRegistrar.additionalArgs` and have Helm template modified to append these additional arguments. This way it's possible to pass any arbitrary arguments and not just `--logging-format=json`.

2024-10-24 08:18 UTC, dmpe commented
Hi @snasovich, I have adjusted the PR as you suggested.

2024-10-24 19:23 UTC, brandond requested changes
ensure that these are quoted

2024-10-24 19:23 UTC, brandond commented on charts/rancher-vsphere-csi/templates/controller/deployment.yaml
> +            - {{ . }}
```suggestion
            - {{ . | quote }}
```

2024-10-24 19:23 UTC, brandond commented on charts/rancher-vsphere-csi/templates/controller/deployment.yaml
> +            - {{ . }}
```suggestion
            - {{ . | quote }}
```

2024-10-24 19:23 UTC, brandond commented on charts/rancher-vsphere-csi/templates/node/daemonset.yaml
> +            - {{ . }}
```suggestion
            - {{ . | quote }}
```

2024-10-24 19:23 UTC, brandond commented on charts/rancher-vsphere-csi/templates/node/daemonset.yaml
> +            - {{ . }}
```suggestion
            - {{ . | quote }}
```

2024-10-24 19:23 UTC, brandond commented on charts/rancher-vsphere-csi/templates/controller/deployment.yaml
> +            - {{ . }}
```suggestion
            - {{ . | quote }}
```

2024-10-24 20:12 UTC, dmpe commented on charts/rancher-vsphere-csi/templates/controller/deployment.yaml
> +            - {{ . }}
thank you.

2024-10-24 20:18 UTC, brandond approved these changes

2024-10-25 16:38 UTC, snasovich approved these changes

2024-10-25 16:38 UTC, merged

2024-10-25 16:41 UTC, snasovich commented
@dmpe , thank you for your contribution to this project. We're going to take care of getting these changes pulled in Rancher/RKE2 charts.

2024-10-25 16:42 UTC, dmpe commented
Thank you @snasovich as well. Will be looking forward to the next release(s).